BlogProject/Controllers/AboutController.cs
using System.Web.Mvc;
using BusinessLayer.Concrete;

namespace BlogProject.Controllers
{
    public class AboutController : Controller
    {
        private readonly AboutManager _aboutManager = new AboutManager();
        private readonly AuthorManager _authorManager = new AuthorManager();
        public ActionResult Index()
        {
            var result = _aboutManager.GetAll();
            return View(result);
        }

        public PartialViewResult Footer()
        {
            var result = _aboutManager.GetAll();
            return PartialView(result);
        }

        public PartialViewResult MeetTheTeam()
        {
            var result = _authorManager.GetAll();
            return PartialView(result);
        }
    }
}

BlogProject/Controllers/AuthorController.cs
using System.Linq;
using System.Web.Mvc;
using BusinessLayer.Concrete;

namespace BlogProject.Controllers
{
    public class AuthorController : Controller
    {
        private readonly BlogManager _blogManager = new BlogManager();
        public PartialViewResult AuthorResult(int id)
        {
            var result = _blogManager.GetAll().FirstOrDefault(x=>x.BlogId==id);
            return PartialView(result);
        }

        public PartialViewResult AuthorPopularPost(int id)
        {
            var authorId=_blogManager.GetAll().Where(x=>x.BlogId==id)
                .Select(y=>y.AuthorId).FirstOrDefault();
            var result = _blogManager.GetBlogsByAuthor(authorId);
            return PartialView(result);
        }
    }
}

BlogProject/Controllers/BlogController.cs
using System.Linq;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using PagedList;

namespace BlogProject.Controllers
{
    public class BlogController : Controller
    {
        private readonly BlogManager _blogManager = new BlogManager();
        private readonly CategoryManager _categoryManager = new CategoryManager();
        // GET: Blog
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult BlogList(int page = 1)
        {
            var blogList = _blogManager.GetAll().ToPagedList(page, 6);
            return PartialView(blogList);
        }

        public PartialViewResult FeaturedPost()
        {
            var postTitle1 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 1).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage1 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 1).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate1 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 1).Select(y => y.CreatedTime).FirstOrDefault();
            ViewBag.postTitle1 = postTitle1;
            ViewBag.postImage1 = postImage1;
            ViewBag.blogDate1 = blogDate1;

            var postTitle2 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 2).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage2 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 2).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate2 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 2).Select(y => y.CreatedTime).FirstOrDefault();
            ViewBag.postTitle2 = postTitle2;
            ViewBag.postImage2 = postImage2;
            ViewBag.blogDate2 = blogDate2;

            var postTitle3 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 3).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage3 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 3).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate3 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 3).Select(y => y.CreatedTime).FirstOrDefault();
            ViewBag.postTitle3 = postTitle3;
            ViewBag.postImage3 = postImage3;
            ViewBag.blogDate3 = blogDate3;

            var postTitle4 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 4).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage4 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 4).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate4 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 4).Select(y => y.CreatedTime).FirstOrDefault();
            ViewBag.postTitle4 = postTitle4;
            ViewBag.postImage4 = postImage4;
            ViewBag.blogDate4 = blogDate4;

            var postTitle5 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 5).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage5 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 5).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate5 = _blogManager.GetAll().OrderByDescending(z => z.BlogId)
                .Where(x => x.CategoryId == 5).Select(y => y.CreatedTime).FirstOrDefault();
            ViewBag.postTitle5 = postTitle5;
            ViewBag.postImage5 = postImage5;
            ViewBag.blogDate5 = blogDate5;

            return PartialView();
        }
        public PartialViewResult OtherFeaturedPost()
        {
            var postTitle1 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 1).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage1 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 1).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate1 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 1).Select(y => y.CreatedTime).FirstOrDefault();
            var categoryName1 = _categoryManager.Get(1).CategoryName;
            ViewBag.postTitle1 = postTitle1;
            ViewBag.postImage1 = postImage1;
            ViewBag.blogDate1 = blogDate1;
            ViewBag.categoryName1 = categoryName1;

            var postTitle2 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 2).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage2 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 2).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate2 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 2).Select(y => y.CreatedTime).FirstOrDefault();
            var categoryName2 = _categoryManager.Get(2).CategoryName;
            ViewBag.postTitle2 = postTitle2;
            ViewBag.postImage2 = postImage2;
            ViewBag.blogDate2 = blogDate2;
            ViewBag.categoryName2 = categoryName2;

            var postTitle3 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 3).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage3 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 3).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate3 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 3).Select(y => y.CreatedTime).FirstOrDefault();
            var categoryName3 = _categoryManager.Get(3).CategoryName;
            ViewBag.postTitle3 = postTitle3;
            ViewBag.postImage3 = postImage3;
            ViewBag.blogDate3 = blogDate3;
            ViewBag.categoryName3 = categoryName3;

            var postTitle4 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 4).Select(y => y.BlogTitle).FirstOrDefault();
            var postImage4 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 4).Select(y => y.BlogImage).FirstOrDefault();
            var blogDate4 = _blogManager.GetAll().OrderBy(z => z.BlogId)
                .Where(x => x.CategoryId == 4).Select(y => y.CreatedTime).FirstOrDefault();
            var categoryName4 = _categoryManager.Get(4).CategoryName;
            ViewBag.postTitle4 = postTitle4;
            ViewBag.postImage4 = postImage4;
            ViewBag.blogDate4 = blogDate4;
            ViewBag.categoryName4 = categoryName4;

            return PartialView();
        }

        public ActionResult BlogDetails()
        {
            return View();
        }

        public PartialViewResult BlogCover(int? id)
        {
            var result = _blogManager.GetAll().FirstOrDefault(x => x.BlogId == id);
            return PartialView(result);
        }

        public PartialViewResult BlogReadAll(int? id)
        {
            if (id != null)
            {
                var result = _blogManager.GetAll().FirstOrDefault(x => x.BlogId == id);
                return PartialView(result);
            }

            return PartialView();
        }

        public ActionResult BlogByCategory(int id, int page = 1)
        {
            var result = _blogManager.GetBlogsByCategory(id).ToPagedList(page, 6);

            var categoryName = result
                .Select(y => y.Category.CategoryName).FirstOrDefault();
            ViewBag.categoryName = categoryName;
            var categoryDescription = result
                .Select(y => y.Category.CategoryDescription).FirstOrDefault();
            ViewBag.categoryDescription = categoryDescription;

            return View(result);
        }

    }
}

BlogProject/Controllers/CategoryController.cs
using System.Web.Mvc;
using BusinessLayer.Concrete;

namespace BlogProject.Controllers
{
    public class CategoryController : Controller
    {
        private readonly CategoryManager _categoryManager = new CategoryManager();
        // GET: Category
        public ActionResult Index()
        {
            var result = _categoryManager.GetAll();
            return View(result);
        }

        public PartialViewResult BlogDetailsCategoryList()
        {
            var result = _categoryManager.GetAll();
            return PartialView(result);
        }
    }
}

BlogProject/Controllers/CommentController.cs
using System.Web.Mvc;
using BusinessLayer.Concrete;
using EntityLayer.Concrete;

namespace BlogProject.Controllers
{
    public class CommentController : Controller
    {
        private readonly CommentManager _commentManager = new CommentManager();
        public PartialViewResult CommentList(int id)
        {
            var result = _commentManager.GetCommentsById(id);
            ViewBag.id = id;
            return PartialView(result);
        }
        [HttpGet]
        public ActionResult LeaveComment(int id)
        {
            ViewBag.id = id;
            return View();
        }
        [HttpPost]
        public ActionResult LeaveComment(Comment comment)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            _commentManager.CommentAdd(comment);
            ModelState.Clear();
            return RedirectToAction("CommentConfirmation");
            return View();
        }
        public ActionResult CommentConfirmation()
        {
            return View();
        }

    }
}

BlogProject/Views/Blog/BlogByCategory.cshtml
@using PagedList.Mvc
@using PagedList
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "BlogByCategory";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="py-5 bg-light">
    <div class="container">
        <div class="row">
           
                <div class="col-md-6">
                    <span>Category</span>
                    <h3>@ViewBag.categoryName</h3>
                    <p> @ViewBag.categoryDescription</p>
                </div>
            

        </div>
    </div>
</div>
<div class="site-section bg-white">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 mb-4">
                    <div class="entry2">
                        <a href="single.html"><img src="@item.BlogImage" style="height:250px" alt="Image" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="post-category text-white bg-secondary mb-3">@item.Category.CategoryName</span>

                            <h2><a href="single.html">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1">By <a href="#">@item.Author.AuthorName</a></span>
                                <span>&nbsp;-&nbsp; @(((DateTime)item.CreatedTime).ToString("yy-MM-dd"))</span>
                            </div>
                            <p> @item.BlogContent.Substring(0,item.BlogContent.Substring(0,200).LastIndexOf(" ", StringComparison.Ordinal)) ...</p>
                            <p><a href="#">Read More</a></p>
                        </div>
                    </div>
                </div>
            }


        </div>
        @Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new {page}))
    </div>
</div>
@Html.Action("Footer", "About")

BlogProject/Views/Blog/BlogCover.cshtml
@model EntityLayer.Concrete.Blog
<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('@Model.BlogImage');">
    <div class="container">
        <div class="row same-height justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="post-entry text-center">
                    <span class="post-category text-white bg-success mb-3">@Html.DisplayFor(m=>m.Category.CategoryName)</span>
                    <h1 class="mb-4"><a href="#"> @Html.DisplayFor(m=>m.BlogTitle)</a></h1>
                    <div class="post-meta align-items-center text-center">
                        <figure class="author-figure mb-0 mr-3 d-inline-block"><img src="@Html.DisplayFor(m=>m.Author.AuthorImage)" alt="Image" class="img-fluid"></figure>
                        <span class="d-inline-block mt-1">@Html.DisplayFor(m=>m.Author.AuthorName)</span>
                        <span>&nbsp;-&nbsp; @(((DateTime)Model.CreatedTime).ToString("yy-MM-dd"))</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BlogProject/Views/Blog/BlogDetails.cshtml
@{
    ViewBag.Title = "BlogDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@Html.Action("BlogCover", "Blog")
<section class="site-section py-lg">
    <div class="container">

        <div class="row blog-entries element-animate">

            <div class="col-md-12 col-lg-8 main-content">
                @Html.Action("BlogReadAll", "Blog")
                @Html.Action("CommentList", "Comment")
            </div>
            <div class="col-md-12 col-lg-4 sidebar">
                @Html.Action("AuthorResult", "Author")
                @Html.Action("AuthorPopularPost", "Author")
                @Html.Action("BlogDetailsCategoryList", "Category")
            </div>
        </div>
    </div>
</section>
@Html.Action("OtherFeaturedPost", "Blog")
@Html.Action("AddMail", "MailSubscribe")
@Html.Action("Footer", "About")

BlogProject/Views/Blog/BlogList.cshtml
@using PagedList.Mvc
@using PagedList
@model IEnumerable<EntityLayer.Concrete.Blog>
@{ string color = "";}
<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-12">
                <h2>Post Listesi</h2>
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                if (item.Category.CategoryName == "Seyahat")
                {
                    color = "post-category text-white bg-info mb-3";
                }else if (item.Category.CategoryName =="Teknoloji")
                {
                    color = "post-category text-white bg-secondary mb-3";
                }
                else if (item.Category.CategoryName == "Yazılım")
                {
                    color = "post-category text-white bg-warning mb-3";
                }
                else if (item.Category.CategoryName == "Spor")
                {
                    color = "post-category text-white bg-danger mb-3";
                }
                else if (item.Category.CategoryName == "Film & Dizi")
                {
                    color = "post-category text-white bg-success mb-3";
                }
                <div class="col-lg-4 mb-4">
                    <div class="entry2">
                        <a href="single.html"><img src="@item.BlogImage" style="height:250px" alt="Image" class="img-fluid rounded"></a>
                        <div class="excerpt">
                            <span class="@color">@item.Category.CategoryName</span>

                            <h2><a href="/Blog/BlogDetails/@item.BlogId">@item.BlogTitle</a></h2>
                            <div class="post-meta align-items-center text-left clearfix">
                                <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                                <span class="d-inline-block mt-1">By <a href="#">@item.Author.AuthorName</a></span>
                                <span>@(((DateTime)item.CreatedTime).ToString("yy-MM-dd"))</span>
                            </div>

                            <p>@item.BlogContent.Substring(0, @item.BlogContent.Substring(0,200).LastIndexOf(" "))...</p>
                            <p><a href="#">Devamını Oku</a></p>
                        </div>
                    </div>
                </div>            }
        </div>
    </div>
</div>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new {page}))

BlogProject/Views/Blog/BlogReadAll.cshtml
@model EntityLayer.Concrete.Blog
<div class="post-content-body">
    <p>@Html.DisplayFor(m=>m.BlogContent)</p>
    <div class="row mb-5 mt-5">
        <div class="col-md-12 mb-4">
            <img src="@Html.DisplayFor(m=>m.BlogImage)" alt="Image placeholder" class="img-fluid rounded">
        </div>
       
    </div>
   
</div>

BlogProject/Views/Blog/FeaturedPost.cshtml
@using System.Web.UI.WebControls
<div class="site-section bg-light">
    <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <div class="col-md-4">
                <a href="single.html" class="h-entry mb-30 v-height gradient" style="background-image: url('@ViewBag.postImage1');">

                    <div class="text">
                        <h2>@ViewBag.postTitle1.</h2>
                        <span class="date">@(((DateTime)ViewBag.blogDate1).ToString("MM/dd/yyyy"))</span>
                    </div>
                </a>
                <a href="single.html" class="h-entry v-height gradient" style="background-image: url('@ViewBag.postImage2');">

                    <div class="text">
                        <h2>@ViewBag.postTitle2</h2>
                        <span class="date">@(((DateTime)ViewBag.blogDate2).ToString("MM/dd/yyyy"))</span>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="single.html" class="h-entry img-5 h-100 gradient" style="background-image: url('@ViewBag.postImage5');">

                    <div class="text">
                        <h2>@ViewBag.postTitle5</h2>
                        <span class="date">@(((DateTime)ViewBag.blogDate5).ToString("MM/dd/yyyy"))</span>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a href="single.html" class="h-entry mb-30 v-height gradient" style="background-image: url('@ViewBag.postImage3');">

                    <div class="text">
                        <h2>@ViewBag.postTitle3</h2>
                        <span class="date">@(((DateTime)ViewBag.blogDate3).ToString("MM/dd/yyyy"))</span>
                    </div>
                </a>
                <a href="single.html" class="h-entry v-height gradient" style="background-image: url('@ViewBag.postImage4');">

                    <div class="text">
                        <h2>@ViewBag.postTitle4</h2>
                        <span class="date">@(((DateTime)ViewBag.blogDate3).ToString("MM/dd/yyyy"))</span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

BlogProject/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<br />
@Html.Action("FeaturedPost", "Blog")
@Html.Action("BlogList", "Blog")
@*@Html.Action("OtherFeaturedPost", "Blog")*@
@Html.Action("AddMail", "MailSubscribe")
@Html.Action("Footer", "About")

BlogProject/Views/Blog/OtherFeaturedPost.cshtml
<div class="site-section bg-light">
    <div class="container">

        <div class="row align-items-stretch retro-layout">

            <div class="col-md-5 order-md-2">
                <a href="single.html" class="hentry img-1 h-100 gradient" style="background-image: url('@ViewBag.postImage1');">
                    <span class="post-category text-white bg-danger">@ViewBag.categoryName1</span>
                    <div class="text">
                        <h2>@ViewBag.postTitle1</h2>
                        <span>@(((DateTime)ViewBag.blogDate1).ToString("yy-MM-dd"))</span>
                    </div>
                </a>
            </div>

            <div class="col-md-7">

                <a href="single.html" class="hentry img-2 v-height mb30 gradient" style="background-image: url('@ViewBag.postImage2');">
                    <span class="post-category text-white bg-success">@ViewBag.categoryName2</span>
                    <div class="text text-sm">
                        <h2>@ViewBag.postTitle2</h2>
                        <span>@(((DateTime)ViewBag.blogDate2).ToString("yy-MM-dd"))</span>
                    </div>
                </a>

                <div class="two-col d-block d-md-flex">
                    <a href="single.html" class="hentry v-height img-2 gradient" style="background-image: url('@ViewBag.postImage3');">
                        <span class="post-category text-white bg-primary">@ViewBag.categoryName3</span>
                        <div class="text text-sm">
                            <h2>@ViewBag.postTitle3</h2>
                            <span>@(((DateTime)ViewBag.blogDate3).ToString("yy-MM-dd"))</span>
                        </div>
                    </a>
                    <a href="single.html" class="hentry v-height img-2 ml-auto gradient" style="background-image: url('@ViewBag.postImage4');">
                        <span class="post-category text-white bg-warning">@ViewBag.categoryName4</span>
                        <div class="text text-sm">
                            <h2>@ViewBag.postTitle4</h2>
                            <span>@(((DateTime)ViewBag.blogDate4).ToString("yy-MM-dd"))</span>
                        </div>
                    </a>
                </div>

            </div>
        </div>

    </div>
</div>